app/projects/models.py
from app import db

# TODO - Import SQLAlchemy and convert class to ORM
class Projects(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    url = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.String(255), nullable=False)
    language = db.Column(db.String(10), nullable=False)
    create_date = db.Column(db.String(50), nullable=False)
    stars = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return "Projects('{name}', '{description}', '{language}', '{create_date}', '{stars}')".format(name=name, description=description, language='language', create_date=create_date, stars=stars)

app/contact/forms.py
from flask import Flask, render_template, flash, redirect, url_for, request
from flask_wtf import Form, RecaptchaField
from wtforms import StringField, validators, TextAreaField

#Contact route creation go to WTForms Documentation
class ContactForm(Form):
    name = StringField('Name', validators=[validators.InputRequired(message='Name is Required!'), validators.Length(min=1, max=50)])
    email = StringField('Email', 
                        validators=[
                            validators.InputRequired(message='Email is Required!'), 
                            validators.Email("This field requires a valid email address"), 
                            validators.Length(min=1, max=100)
                        ]
    )
    subject = StringField('Subject', 
                          validators=[
                              validators.InputRequired(message='Subject is Required!'), 
                              validators.Length(min=4, max=100)
                            ]
    )
    message = TextAreaField('Message', 
                            validators=[
                                validators.InputRequired(message='Message is Required!')
                            ], 
                            render_kw={
                                "rows": 5
                            }
    )
    recaptcha = RecaptchaField()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect
from flask_mail import Mail, Message

from app.config import Config

app = Flask(__name__)
app.config.from_object(Config)

csrf = CSRFProtect(app)
db = SQLAlchemy(app)
mail = Mail(app)

from app import routes

from app.index.views import main
from app.projects.views import projects
from app.resume.views import resume
from app.contact.views import contact

app.register_blueprint(main, url_prefix='/')
app.register_blueprint(projects, url_prefix='/projects')
app.register_blueprint(resume, url_prefix='/resume')
app.register_blueprint(contact, url_prefix='/contact')

app/contact/views.py
from flask import Blueprint, render_template, make_response, request, flash
from flask_mail import Mail, Message
from flask_wtf import Form
from wtforms import StringField, TextAreaField, validators
from datetime import datetime
from app import app, mail

from app.contact.forms import ContactForm

contact = Blueprint('contact', __name__,
                     template_folder='./templates')

@contact.route('/', methods=['GET', 'POST'])
def index():
    form = ContactForm()

    if request.method == 'POST' and form.validate_on_submit():
        msg = Message(subject=request.form['subject'],
                    sender='MichaelLeone.io <' + app.config.get("MAIL_USERNAME") + '>',
                    recipients=["msleone90@gmail.com"])

        # TODO work on template            
        msg.html = render_template('contact_email.html', name=request.form['name'], email=request.form['email'], body=request.form['message'])
        mail.send(msg)

        flash('Email was sent successfully!', 'success')
    
    return render_template('contact.html', now=datetime.utcnow(), form=form)

app/index/views.py
from flask import Blueprint, render_template, make_response, request, flash
from datetime import datetime

from app import app

main = Blueprint('index', __name__, template_folder='../index/templates')

#mail = Mail(app)

@main.route('/')
def index():
    return render_template('index.html', now=datetime.utcnow())

app/projects/views.py
from flask import Blueprint, render_template, make_response, request, flash
from datetime import datetime

from app.projects.models import Projects

projects = Blueprint('projects', __name__, template_folder='../projects/templates')

@projects.route('/')
def index():
    projects = Projects.query.all()

    return render_template('projects.html', now=datetime.utcnow(), projects=projects)

app/resume/views.py
from flask import Blueprint, render_template, make_response, request, flash
from datetime import datetime

resume = Blueprint('resume', __name__, template_folder='../resume/templates')

@resume.route('/resume')
def index():
    return render_template('resume.html', now=datetime.utcnow())

app/routes.py
from flask import render_template, make_response, request, flash
from flask_mail import Mail, Message
from flask_wtf import Form
from wtforms import StringField, TextAreaField, validators
from datetime import datetime

from app import app

@app.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('404.html'), 404

app/templates/includes/_formhelpers.html
{% macro render_field(field) %}
{{ field.label }}
{{ field(**kwargs)|safe }}
{% if field.errors %}
  {% for error in field.errors %}
    <span class="help-inline" style="color: red">{{ error }}</span>
  {% endfor %}
{% endif %}
{% endmacro %}

app/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
    <div class="alert alert-{{ category }}">{{ message }}</div>
  {% endfor %}
{% endif %}
{% endwith %}

{% if msg %}
    <div class="alert alert-{{ msgType }}">{{msg}}</div>
{% endif %}

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <!-- Header -->
    <input type="hidden" id="page" value="index">

    <header class="masthead">
      <div class="container d-flex h-100 align-items-center">
        <div class="mx-auto text-center main-container">
          <h1 class="mx-auto my-0 text-uppercase">Michael Leone</h1>
          <h2 class="text-white-50 mx-auto mt-2 mb-5 main-text">Technology Enthusiast/Software Developer from Atlanta, GA.</h2>
        </div>
      </div>
    </header>

    <div class="read-more">
      <h4><a class="js-scroll-trigger read-link" href="#about">Read More</a></h4>
      <a class="js-scroll-trigger" href="#about"><img alt="Arrow Down Icon" style="height: 70px;" src="{{ url_for('static', filename='img/Down.jpg') }}"></a>
    </div>
  
      <!-- About Section -->
      <section id="about" class="about-section text-center">
        <div class="container">
          <div class="row">              
            <div class="col-lg-8 mx-auto">
              <img class="img-fluid img-circle" src="{{ url_for('static', filename='img/profile1.png') }}" alt="">
              <br>
              <h2 class="text-white mb-4">About Me</h2>
              <p class="text-white-50" style="text-align: justify;">
                My name is Michael Leone and I am 29 years old and live in Atlanta, GA. 
                I enjoy learning and keeping up to date with the latest trends and tools in the IT industry. 
                I'm experienced with working with the AWS cloud, web application development, database management 
                and front end web design. As the development lead across three internal web applications, I'm spearheading the effort 
                for migrating these applications into AWS. I'm determined and enthusiastic about my job duties 
                while committed to deliver the best result possible. I also strive to be approachable and dependable 
                among my coworkers and know how to have fun.
              </p>
            </div>
          </div>
        </div>
      </section>
  
      <!-- Projects Section -->
      <section id="projects" class="projects-section bg-light">
        <div class="container">
  
          <!-- Featured Project Row -->
          <div class="row align-items-center no-gutters mb-4 mb-lg-5">
            <div class="col-xl-8 col-lg-8">
              <div class="text-center text-lg-left">
                <h4>Future Goals/Ventures (For 2019)</h4>
                <ul>
                  <li>
                    Microservices
                  </li>
                  <li>
                    Mobile Application Development
                  </li>
                  <li>
                    Continuous Integration/Continuous Deployment
                  </li>
                  <li>
                    Machine Learning/AI
                  </li>
                  <li>
                    Serverless Architecture
                  </li>
                  <li>
                    AutoScaling
                  </li>
                  <li>
                    Security
                  </li>
                  <li>
                    Blockchain
                  </li>
                </ul>
              </div>
            </div>
            <div class="text-center text-lg-left">
              <img src="{{ url_for('static', filename='img/programming.png') }}" alt="" style="height: 200px; width: 200px;">
            </div>
          </div>
          
          <div class="row align-items-center no-gutters mb-4 mb-lg-5">
            <p>Outside of technology, I'm an avid sports fan and passionate supporter of Atlanta teams.</p>
          </div>

        </div>
      </section>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Michael Leone</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/grayscale.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/site-favicon.ico') }}" type="image/x-icon">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  </head>

  <body id="page-top">

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}
  
      <!-- Social Section -->
      <section class="contact-section">
          <div class="container">
            <div class="col-md-10 col-lg-8 mx-auto text-center">
                <h2 class="text-white mb-5">SOCIAL</h2>
                <p class="text-white mb-5">
                    Follow for updates.
                </p>
            </div>
    
            <div class="social d-flex justify-content-center">
              <a href="https://twitter.com/msleone90" target="_blank"class="mx-2">
                <i class="fa fa-twitter"></i>
              </a>
              <a href="https://www.facebook.com/msleone90" target="_blank" class="mx-2">
                <i class="fa fa-facebook"></i>
              </a>
              <a href="https://www.linkedin.com/in/mleone1/" target="_blank" class="mx-2">
                <i class="fa fa-linkedin"></i>
              </a>
              <a href="https://github.com/msleone90" target="_blank" class="mx-2">
                <i class="fa fa-github"></i>
              </a>
            </div>
    
          </div>
        </section>

    <!-- Footer -->
    <footer class="bg-black small text-center footer">
      <div class="container">
        Copyright &copy; Michael Leone {{ now.year }}
      </div>
    </footer>

    <!-- JS Scripts-->
    <script src="{{ url_for('static', filename='js/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-1.9.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/grayscale.min.js') }}"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>


    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Plugin JavaScript -->
    <script src="{{ url_for('static', filename='js/jquery.easing.min.js') }}"></script>

  </body>

</html>

app/templates/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/">Michael Leone</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{ url_for('projects.index') }}">Projects</a>
          </li>
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{ url_for('resume.index') }}">Resume</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{ url_for('contact.index') }}">Contact</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>